const pagarConta = require('./map');
const {
    startPagarConta,
    impedido,
    saudacaoURA,
    transfereParaATH,
    encaminhaFluxoContratarPacotes,
    encerraLigacao,
    viaDeAcesso,
    verificaProprioAparelho,
    verificaSenhaUnica,
    perguntaQuerAlgoMais,
    desambiguador,
    agradeceDesliga,
    btt,
    dizBloqFinanceiro,
    mais1Fatura,
    mais1FaturaNao,
    mais1FaturaSim,
    mainClienteTitular,
    mainClienteTitularMais1,
    servicoCodigoBarras7,
    servicoCodigoBarras1,
    servicoCodigoBarras1Mais1,
    enviaFaturasSMS,
    enviaFaturasSMSMais1,
    servicoLinkNegocia2,
    enviaLinkNegocia,
    podeAcessarFaturasNoSite,
    bto,
    elegivelReliga,
    btoClienteTitular,
    veioFluxoInformaContaPaga,
    naoInformouContaPaga,
    ofereceReliga,
    respostaOfereceReliga,
    servicoReliga,
    respNaoETitular,
    motivoBloq,
    motivoBloqQuebra,
    motivoBloq24h,
    quebraTitular,
    servicoLinkNegocia6,
    SucessoLinkNegocia6,
    querFaturaBloq,
    servicoCodigoBarras5,
    expectFalhaCodBarra5,
    ofereceATH,
    expectSucessoCodBarras5,
    maisDe1FaturaAberto,
    expectOfereceFatAberto,
    querReceberFatEmAberto,
    enviaDemaisFaturas,
    expectEnviaDemaisFaturas,
    ultimas24hTitular,
    expectTitular24h,
    expectNaoTitular24h,
    querFaturaBloqNaoTitular,
    falhaLinkNegocia6,
    expectNaoQuerFatura,
    falhaServicoReliga,
    expectPerguntaDificuldade,
    possuiDificuldade,
    expectPerguntaQualDificuldade,
    qualDificuldade,
    servicoConsultaDados,
    internetReduzida,
    billingProfile,
    expectVelocidadeReduzida,
    querSaberDosPacotes,
    expectNavegacaoNormal,
    continuarOuATH,
    jaReiniciou,
    enviaGuiaApararelho,
    expectSucessoEnvioGuia,
    expectFalhaEnvioGuia,
    insisteReinicio,
    expectContinuarOuATH,
    expectQuerSaberDosPacotes,
    expectInsisteReinicio,
    veioDeNaoRecebimentoFatura,
    expectNaoRecebimentoFatura,
    contaDigital,
    expectContaDigital,
    expectNaoContaDigital,
    faturaEmAberto,
    intencaoCodigoBarras,
    aceitaCodBarras,
    expectNaoAceitaCodBarra,
    clienteInsiste,
    insisteFaturasAberto,
    insisteFaturasAbertoNao,
    insisteFaturasAbertoSim,
    expectNaoPossuiFaturaAberto
} = require('./nodes');

pagarConta.linkChain(
    // comum
    [perguntaQuerAlgoMais.getPath('Não quer mais nada'), agradeceDesliga],

// serviços
    // Serviço Código de Barras (7)
    [servicoCodigoBarras7.getPath('* Falha Serviço Cód.Barras'), podeAcessarFaturasNoSite],
        [podeAcessarFaturasNoSite, perguntaQuerAlgoMais],
    // Serviço Código de Barras (5)
    [servicoCodigoBarras5.getPath('* Falha Serviço Cód.Barras/SMS'), expectFalhaCodBarra5],
        [expectFalhaCodBarra5, ofereceATH],
            [ofereceATH.getPath('Aceita ir para ATH'), transfereParaATH],
            [ofereceATH.getPath('Não quer falar com ATH'), perguntaQuerAlgoMais],

        
    // Serviço Código de Barras e fatura por SMS(1)
    [servicoCodigoBarras1.getPath('* Falha Serviço Cód.Barras/Fatura'), podeAcessarFaturasNoSite],
    [servicoCodigoBarras1Mais1.getPath('* Falha Serviço Cód.Barras/Fatura'), podeAcessarFaturasNoSite],
    // Serviço Negocia
    [servicoLinkNegocia2.getPath('* Falha SMS (Link Negocia)'), perguntaQuerAlgoMais],
    [servicoLinkNegocia6.getPath('* Falha SMS (Link Negocia)'), falhaLinkNegocia6],
        [falhaLinkNegocia6, querFaturaBloq],
        [querFaturaBloq.getPath('* Não quer fatura do bloqueio'), perguntaQuerAlgoMais],
        // [expectNaoQuerFatura, perguntaQuerAlgoMais],
    // Serviço Religa
    [servicoReliga.getPath('* Falha no Religa'), falhaServicoReliga],
        [falhaServicoReliga, perguntaQuerAlgoMais],
    // Serviço Consulta Dados
    [servicoConsultaDados.getPath('* Falha na Consulta de Dados'), jaReiniciou],
    [jaReiniciou.getPath('Já reiniciou'), enviaGuiaApararelho],
    [jaReiniciou.getPath('Não reiniciou'), expectInsisteReinicio],
    [expectInsisteReinicio, insisteReinicio],
        [insisteReinicio.getPath('Aceita Reiniciar'), agradeceDesliga],
        [insisteReinicio.getPath('Não quer reiniciar'), enviaGuiaApararelho],
    // Serviço Billing
    [billingProfile.getPath('* Falha no billing'), expectQuerSaberDosPacotes],
    [expectQuerSaberDosPacotes, querSaberDosPacotes],
        [querSaberDosPacotes.getPath('Quer pacote adicional'), encaminhaFluxoContratarPacotes],
        [querSaberDosPacotes.getPath('Não quer pacote adicional'), perguntaQuerAlgoMais],
    // Serviço Guia de Aparelhos
    [enviaGuiaApararelho.getPath('* Sucesso no Envio do Guia'), expectSucessoEnvioGuia],
    [expectSucessoEnvioGuia, perguntaQuerAlgoMais],
    [enviaGuiaApararelho.getPath('* Falha no Envio do Guia'), expectFalhaEnvioGuia],
        [expectFalhaEnvioGuia, perguntaQuerAlgoMais],
    

    [startPagarConta, billingProfile],
        [billingProfile.getPath('* Sucesso no billing'), veioDeNaoRecebimentoFatura],
            [veioDeNaoRecebimentoFatura.getPath('Veio de #desambiguadorNaoRecebimentoDeFatura'), expectNaoRecebimentoFatura],
                [expectNaoRecebimentoFatura, contaDigital],
                    [contaDigital.getPath('* É conta digital'), expectContaDigital],
                        [expectContaDigital, mainClienteTitular],
                    [contaDigital.getPath('* Não é conta digital'), expectNaoContaDigital],
                        [expectNaoContaDigital, mainClienteTitular],
                        //
            [veioDeNaoRecebimentoFatura.getPath('Não veio de #desambiguadorNaoRecebimentoDeFatura').noStepMessage(), mainClienteTitular],
            [mainClienteTitular.getPath('* Não é titular'), faturaEmAberto],
                [faturaEmAberto.getPath('* Possui fatura em aberto'), intencaoCodigoBarras],
                [intencaoCodigoBarras.getPath('VEIO DE DESAMBIGUADOR CODIGOBARRAS'), servicoCodigoBarras5],
                    [servicoCodigoBarras5.getPath('* Sucesso Serviço Cód.Barras/SMS'), maisDe1FaturaAberto],
                        [maisDe1FaturaAberto.getPath('* Não possui mais de 1 fatura em aberto'), mais1FaturaNao],
                            [mais1FaturaNao, perguntaQuerAlgoMais],
                        [maisDe1FaturaAberto.getPath('* Possui mais de 1 fatura em aberto'), mais1FaturaSim],
                            [mais1FaturaSim, perguntaQuerAlgoMais],
                [intencaoCodigoBarras.getPath('Não veio de desambiguadorCodigoBarras'), expectOfereceFatAberto],
                [expectOfereceFatAberto, aceitaCodBarras],
                    [aceitaCodBarras.getPath('Aceita receber Código de Barras'), servicoCodigoBarras5],
                    [aceitaCodBarras.getPath('Não aceita receber Código de Barras'), expectNaoAceitaCodBarra],
                        [expectNaoAceitaCodBarra, clienteInsiste],
                            [clienteInsiste.getPath('Quer algo mais: #desambiguadorCodigoBarras ou SegundaVia ou Pagar Conta ou NaoRecebimentoFatura'), insisteFaturasAberto],
                                [insisteFaturasAberto.getPath('* (insistencia) Não possui faturas em aberto'), insisteFaturasAbertoNao],
                                    [insisteFaturasAbertoNao, perguntaQuerAlgoMais],
                                [insisteFaturasAberto.getPath('* (insistencia) Possui faturas em aberto'), insisteFaturasAbertoSim],
                                    [insisteFaturasAbertoSim, perguntaQuerAlgoMais],
                            [clienteInsiste.getPath('Não quer mais nada').noStepMessage(), perguntaQuerAlgoMais],
            //     // CONTINUAR DAQUI
                [faturaEmAberto.getPath('* Não possui fatura em aberto'), expectNaoPossuiFaturaAberto],
                    [expectNaoPossuiFaturaAberto, perguntaQuerAlgoMais],
            // [mainClienteTitular.getPath('* É titular'), mainClienteTitular],



        [billingProfile.getPath('* Falha no billing'), viaDeAcesso],
    

)


pagarConta.mapScenarios();
pagarConta.showScenarios();
pagarConta.exportScenariosToExcel();