const pagarConta = require('./map');
const {
    startPagarConta,
 impedido,
 saudacaoURA,
 transfereParaATH,
 encaminhaFluxoContratarPacotes,
 encerraLigacao,
 viaDeAcesso,
 verificaProprioAparelho,       
 verificaSenhaUnica,
 perguntaQuerAlgoMais,
 desambiguador,
 agradeceDesliga,
 btt,
 dizBloqFinanceiro,
 mais1Fatura,
 mais1FaturaNao,
 mais1FaturaSim,
 mainClienteTitular,
 mainClienteTitularMais1,
 servicoCodigoBarras7,
 servicoCodigoBarras1,
 servicoCodigoBarras1Mais1,
 enviaFaturasSMS,
 enviaFaturasSMSMais1,
 servicoLinkNegocia2,
 enviaLinkNegocia,
 podeAcessarFaturasNoSite,
 bto,
 elegivelReliga,
 btoClienteTitular,
 veioFluxoInformaContaPaga,
 naoInformouContaPaga,
 ofereceReliga,
 respostaOfereceReliga,
 servicoReliga,
 respNaoETitular,
 motivoBloq,
 motivoBloqQuebra,
 motivoBloq24h,
 quebraTitular,
 servicoLinkNegocia6,
 SucessoLinkNegocia6,
 querFaturaBloq,
 servicoCodigoBarras5,
 servicoCodigoBarras52,
 expectFalhaCodBarra5,
 ofereceATH,
 expectSucessoCodBarras5,
 maisDe1FaturaAberto,
 expectOfereceFatAberto,
 querReceberFatEmAberto,
 enviaDemaisFaturas,
 expectEnviaDemaisFaturas,
 ultimas24hTitular,
 expectTitular24h,
 expectNaoTitular24h,
 querFaturaBloqNaoTitular,
 falhaLinkNegocia6,
 falhaLinkNegocia2,
 expectNaoQuerFatura,
 falhaServicoReliga,
 expectPerguntaDificuldade,
 possuiDificuldade,
 expectPerguntaQualDificuldade,
 qualDificuldade,
 servicoConsultaDados,
 internetReduzida,
 billingProfile,
 expectVelocidadeReduzida,
 querSaberDosPacotes,
 expectNavegacaoNormal,
 continuarOuATH,
 jaReiniciou,
 enviaGuiaApararelho,
 expectSucessoEnvioGuia,
 expectFalhaEnvioGuia,
 insisteReinicio,
 expectContinuarOuATH,
 expectQuerSaberDosPacotes,
 expectInsisteReinicio,
 veioDeNaoRecebimentoFatura,
 expectNaoRecebimentoFatura,
 contaDigital,
 expectContaDigital,
 expectNaoContaDigital,
 faturaEmAberto,
 intencaoCodigoBarras,
 aceitaCodBarras,
 expectNaoAceitaCodBarra,
 clienteInsiste,
 insisteFaturasAberto,
 insisteFaturasAbertoNao,
 insisteFaturasAbertoSim,
 expectNaoPossuiFaturaAberto,
 pediuAlgumMes,
 mesPossuiFaturaAberto,
 faturaUltimos12meses,
 expectNaoUltimos12meses,
 expectNaoUltimos12mesesAlt,
 faturaUltimos6meses,
 faturaUltimos6mesesAlt,
 expectNaoUltimos6meses,
 expectNaoUltimos6mesesAlt,
 querContinuarURA,
 querContinuarURAAlt,
 querContinuarURA2,
 emailValido,
 expectEmailInvalido,
 expectEmailInvalidoAlt,
 expectComoPrefere,
 expectComoPrefereAlt,
 escolhaRealizada,
 escolhaRealizadaAlt,
 verificaProprioAparelhoSMS,
 verificaProprioAparelhoSMSAlt,
 verificaProprioAparelhoSMSAlt2,
 verificaProprioAparelhoEmail,
 verificaProprioAparelhoEmailAlt,
 verificaProprioAparelhoCasa,
 verificaProprioAparelhoCasaAlt,
 servicoFaturaSMS1,
 servicoFaturaSMS1Alt,
 servicoFaturaEmail1,
 servicoFaturaEmail1Alt,
 servicoFaturaCasa1,
 servicoFaturaCasa1Alt,
 existemFaturasAbertoSMS,
 expectFalhaEmail,
 expectFalhaCasa,
 existemFaturasAbertoEmail,
 existemFaturasAbertoCasa,
 clienteContaDigital,
 expectTratNaoRecebimento,
 expectFaturasEmAbertoSMS,
 expectFaturasEmAbertoEmail,
 expectFaturasEmAbertoCasa,
 querReceberFatEmAbertoSMS,
 querReceberFatEmAbertoEmail,
 querReceberFatEmAbertoCasa,
 enviaFaturasEmAbertoSMS,
 enviaFaturasEmAbertoEmail,
 enviaFaturasEmAbertoCasa,
 expectOutroAparelhoSMS,
 expectOutroAparelhoSMSAlt,
 expectOutroAparelhoSMSAlt2,
 expectOutroAparelhoEmail,
 expectOutroAparelhoEmailAlt,
 expectOutroAparelhoCasa,
 expectOutroAparelhoCasaAlt,
 fluxoSenha2,
 fluxoSenhaSMS,
 fluxoSenhaSMSAlt,
 fluxoSenhaSMSAlt2,
 fluxoSenhaEmail,
 fluxoSenhaEmailAlt,
 fluxoSenhaCasa,
 fluxoSenhaCasaAlt,
 expectEscolheCasa,
 expectEscolheCasaAlt,
 confirmaCasa,
 confirmaCasaAlt,
 expectSegundaChance,
 ofereceSegundaChance,
 semMesFaturaAberto,
 expectSemMesNaoPossuiFatura,
 precisaSegundaVia,
 expectPrecisaSegundaVia,
 qualMesSegundaVia,
 expectMesInvalido,
 segundaTentativaMes,
 emailValido2,
 expectEmailInvalido2,
 expectComoPrefere2,
 escolhaRealizada2,
 verificaProprioAparelhoSMS2,
 verificaProprioAparelhoEmail2,
 verificaProprioAparelhoCasa2,
 servicoFaturaSMS12,
 servicoFaturaEmail12,
 servicoFaturaCasa12,
 faturaUltimos12mesesAlt,
 faturaUltimos6meses2,
 verificaProprioAparelho2,
 enviaLinkSite,
 macete,
 emailValidoAlt,
 startPagarContaERRO,
 impedidoERRO,
 saudacaoURAERRO,
 transfereParaATHERRO,
 encaminhaFluxoContratarPacotesERRO,
 encerraLigacaoERRO,
 viaDeAcessoERRO,
 verificaProprioAparelhoERRO,
 verificaSenhaUnicaERRO,
 perguntaQuerAlgoMaisERRO,
 desambiguadorERRO,
 agradeceDesligaERRO,
 bttERRO,
 dizBloqFinanceiroERRO,
 mais1FaturaERRO,
 mais1FaturaNaoERRO,
 mais1FaturaSimERRO,
 mainClienteTitularERRO,
 mainClienteTitularMais1ERRO,
 servicoCodigoBarras7ERRO,
 servicoCodigoBarras1ERRO,
 servicoCodigoBarras1Mais1ERRO,
 enviaFaturasSMSERRO,
 enviaFaturasSMSMais1ERRO,
 servicoLinkNegocia2ERRO,
 enviaLinkNegociaERRO,
 podeAcessarFaturasNoSiteERRO,
 btoERRO,
 elegivelReligaERRO,
 btoClienteTitularERRO,
 veioFluxoInformaContaPagaERRO,
 naoInformouContaPagaERRO,
 ofereceReligaERRO,
 respostaOfereceReligaERRO,
 servicoReligaERRO,
 respNaoETitularERRO,
 motivoBloqERRO,
 motivoBloqQuebraERRO,
 motivoBloq24hERRO,
 quebraTitularERRO,
 servicoLinkNegocia6ERRO,
 SucessoLinkNegocia6ERRO,
 querFaturaBloqERRO,
 servicoCodigoBarras5ERRO,
 servicoCodigoBarras52ERRO,
 expectFalhaCodBarra5ERRO,
 ofereceATHERRO,
 expectSucessoCodBarras5ERRO,
 maisDe1FaturaAbertoERRO,
 expectOfereceFatAbertoERRO,
 querReceberFatEmAbertoERRO,
 enviaDemaisFaturasERRO,
 expectEnviaDemaisFaturasERRO,
 ultimas24hTitularERRO,
 expectTitular24hERRO,
 expectNaoTitular24hERRO,
 querFaturaBloqNaoTitularERRO,
 falhaLinkNegocia6ERRO,
 falhaLinkNegocia2ERRO,
 expectNaoQuerFaturaERRO,
 falhaServicoReligaERRO,
 expectPerguntaDificuldadeERRO,
 possuiDificuldadeERRO,
 expectPerguntaQualDificuldadeERRO,
 qualDificuldadeERRO,
 servicoConsultaDadosERRO,
 internetReduzidaERRO,
 billingProfileERRO,
 expectVelocidadeReduzidaERRO,
 querSaberDosPacotesERRO,
 expectNavegacaoNormalERRO,
 continuarOuATHERRO,
 jaReiniciouERRO,
 enviaGuiaApararelhoERRO,
 expectSucessoEnvioGuiaERRO,
 expectFalhaEnvioGuiaERRO,
 insisteReinicioERRO,
 expectContinuarOuATHERRO,
 expectQuerSaberDosPacotesERRO,
 expectInsisteReinicioERRO,
 veioDeNaoRecebimentoFaturaERRO,
 expectNaoRecebimentoFaturaERRO,
 contaDigitalERRO,
 expectContaDigitalERRO,
 expectNaoContaDigitalERRO,
 faturaEmAbertoERRO,
 intencaoCodigoBarrasERRO,
 aceitaCodBarrasERRO,
 expectNaoAceitaCodBarraERRO,
 clienteInsisteERRO,
 insisteFaturasAbertoERRO,
 insisteFaturasAbertoNaoERRO,
 insisteFaturasAbertoSimERRO,
 expectNaoPossuiFaturaAbertoERRO,
 pediuAlgumMesERRO,
 mesPossuiFaturaAbertoERRO,
 faturaUltimos12mesesERRO,
 expectNaoUltimos12mesesERRO,
 expectNaoUltimos12mesesAltERRO,
 faturaUltimos6mesesERRO,
 faturaUltimos6mesesAltERRO,
 expectNaoUltimos6mesesERRO,
 expectNaoUltimos6mesesAltERRO,
 querContinuarURAERRO,
 querContinuarURAAltERRO,
 querContinuarURA2ERRO,
 emailValidoERRO,
 expectEmailInvalidoERRO,
 expectEmailInvalidoAltERRO,
 expectComoPrefereERRO,
 expectComoPrefereAltERRO,
 escolhaRealizadaERRO,
 escolhaRealizadaAltERRO,
 verificaProprioAparelhoSMSERRO,
 verificaProprioAparelhoSMSAltERRO,
 verificaProprioAparelhoSMSAlt2ERRO,
 verificaProprioAparelhoEmailERRO,
 verificaProprioAparelhoEmailAltERRO,
 verificaProprioAparelhoCasaERRO,
 verificaProprioAparelhoCasaAltERRO,
 servicoFaturaSMS1ERRO,
 servicoFaturaSMS1AltERRO,
 servicoFaturaEmail1ERRO,
 servicoFaturaEmail1AltERRO,
 servicoFaturaCasa1ERRO,
 servicoFaturaCasa1AltERRO,
 existemFaturasAbertoSMSERRO,
 expectFalhaEmailERRO,
 expectFalhaCasaERRO,
 existemFaturasAbertoEmailERRO,
 existemFaturasAbertoCasaERRO,
 clienteContaDigitalERRO,
 expectTratNaoRecebimentoERRO,
 expectFaturasEmAbertoSMSERRO,
 expectFaturasEmAbertoEmailERRO,
 expectFaturasEmAbertoCasaERRO,
 querReceberFatEmAbertoSMSERRO,
 querReceberFatEmAbertoEmailERRO,
 querReceberFatEmAbertoCasaERRO,
 enviaFaturasEmAbertoSMSERRO,
 enviaFaturasEmAbertoEmailERRO,
 enviaFaturasEmAbertoCasaERRO,
 expectOutroAparelhoSMSERRO,
 expectOutroAparelhoSMSAltERRO,
 expectOutroAparelhoSMSAlt2ERRO,
 expectOutroAparelhoEmailERRO,
 expectOutroAparelhoEmailAltERRO,
 expectOutroAparelhoCasaERRO,
 expectOutroAparelhoCasaAltERRO,
 fluxoSenha2ERRO,
 fluxoSenhaSMSERRO,
 fluxoSenhaSMSAltERRO,
 fluxoSenhaSMSAlt2ERRO,
 fluxoSenhaEmailERRO,
 fluxoSenhaEmailAltERRO,
 fluxoSenhaCasaERRO,
 fluxoSenhaCasaAltERRO,
 expectEscolheCasaERRO,
 expectEscolheCasaAltERRO,
 confirmaCasaERRO,
 confirmaCasaAltERRO,
 expectSegundaChanceERRO,
 ofereceSegundaChanceERRO,
 semMesFaturaAbertoERRO,
 expectSemMesNaoPossuiFaturaERRO,
 precisaSegundaViaERRO,
 expectPrecisaSegundaViaERRO,
 qualMesSegundaViaERRO,
 expectMesInvalidoERRO,
 segundaTentativaMesERRO,
 emailValido2ERRO,
 expectEmailInvalido2ERRO,
 expectComoPrefere2ERRO,
 escolhaRealizada2ERRO,
 verificaProprioAparelhoSMS2ERRO,
 verificaProprioAparelhoEmail2ERRO,
 verificaProprioAparelhoCasa2ERRO,
 servicoFaturaSMS12ERRO,
 servicoFaturaEmail12ERRO,
 servicoFaturaCasa12ERRO,
 faturaUltimos12mesesAltERRO,
 faturaUltimos6meses2ERRO,
 verificaProprioAparelho2ERRO,
 enviaLinkSiteERRO,
 maceteERRO,
 emailValidoAltERRO
} = require('./nodes');

pagarConta.linkChain(
    // comum
    [perguntaQuerAlgoMais.getPath('Não quer mais nada'), agradeceDesliga],

// serviços
    // Serviço Código de Barras (7)
    [servicoCodigoBarras7.getPath('* Falha Serviço Cód.Barras'), podeAcessarFaturasNoSite],
        [podeAcessarFaturasNoSite, perguntaQuerAlgoMais],
    // Serviço Código de Barras (5)
    [servicoCodigoBarras5.getPath('* Falha Serviço Cód.Barras/SMS'), expectFalhaCodBarra5],
        [expectFalhaCodBarra5, ofereceATH],
            [ofereceATH.getPath('Aceita ir para ATH'), transfereParaATH],
            [ofereceATH.getPath('Não quer falar com ATH'), perguntaQuerAlgoMais],
        
    // Serviço Código de Barras e fatura por SMS(1)
    [servicoCodigoBarras1.getPath('* Falha Serviço Cód.Barras/Fatura'), podeAcessarFaturasNoSite],
    [servicoCodigoBarras1Mais1.getPath('* Falha Serviço Cód.Barras/Fatura'), podeAcessarFaturasNoSite],
    // Serviço Negocia
    [servicoLinkNegocia2.getPath('* Falha SMS (Link Negocia)'), falhaLinkNegocia2],
        [falhaLinkNegocia2, ofereceATH],
    [servicoLinkNegocia6.getPath('* Falha SMS (Link Negocia)'), falhaLinkNegocia6],
        [falhaLinkNegocia6, querFaturaBloq],
        [querFaturaBloq.getPath('* Não quer fatura do bloqueio'), perguntaQuerAlgoMais],
        // [expectNaoQuerFatura, perguntaQuerAlgoMais],
    // Serviço Religa
    [servicoReliga.getPath('* Falha no Religa'), falhaServicoReliga],
        [falhaServicoReliga, perguntaQuerAlgoMais],
    // Serviço Consulta Dados
    [servicoConsultaDados.getPath('* Falha na Consulta de Dados'), jaReiniciou],
    [jaReiniciou.getPath('Já reiniciou'), enviaGuiaApararelho],
    [jaReiniciou.getPath('Não reiniciou'), expectInsisteReinicio],
    [expectInsisteReinicio, insisteReinicio],
        [insisteReinicio.getPath('Aceita Reiniciar'), agradeceDesliga],
        [insisteReinicio.getPath('Não quer reiniciar'), enviaGuiaApararelho],
    // // Serviço Billing
    // [billingProfile.getPath('* Falha no billing'), expectQuerSaberDosPacotes],
    // [expectQuerSaberDosPacotes, querSaberDosPacotes],
    //     [querSaberDosPacotes.getPath('Quer pacote adicional'), encaminhaFluxoContratarPacotes],
    //     [querSaberDosPacotes.getPath('Não quer pacote adicional'), perguntaQuerAlgoMais],
    // Serviço Guia de Aparelhos
    [enviaGuiaApararelho.getPath('* Sucesso no Envio do Guia'), expectSucessoEnvioGuia],
    [expectSucessoEnvioGuia, perguntaQuerAlgoMais],
    [enviaGuiaApararelho.getPath('* Falha no Envio do Guia'), expectFalhaEnvioGuia],
        [expectFalhaEnvioGuia, perguntaQuerAlgoMais],
    // Serviço Email
    [servicoFaturaEmail1.getPath('* Falha no serviço Email'), expectFalhaEmail],
        [expectFalhaEmail, ofereceATH],
    // Serviço Correios
    [servicoFaturaCasa1.getPath('* Falha no serviço Correios'), expectFalhaCasa],
        [expectFalhaCasa, ofereceATH],   



    [startPagarConta, billingProfile],
        [billingProfile.getPath('* Sucesso no billing'), veioDeNaoRecebimentoFatura],
            [veioDeNaoRecebimentoFatura, mainClienteTitular],
            [mainClienteTitular.getPath('* Não é titular'), faturaEmAberto],
                [faturaEmAberto.getPath('* Possui fatura em aberto'), intencaoCodigoBarras],
                [intencaoCodigoBarras.getPath('VEIO DE DESAMBIGUADOR CODIGOBARRAS'), servicoCodigoBarras5],
                    [servicoCodigoBarras5.getPath('* Sucesso Serviço Cód.Barras/SMS'), maisDe1FaturaAberto],
                        [maisDe1FaturaAberto.getPath('* Não possui mais de 1 fatura em aberto'), mais1FaturaNao],
                            [mais1FaturaNao, perguntaQuerAlgoMais],
                        [maisDe1FaturaAberto.getPath('* Possui mais de 1 fatura em aberto'), mais1FaturaSim],
                            [mais1FaturaSim, perguntaQuerAlgoMais],
                [intencaoCodigoBarras.getPath('Não veio de desambiguadorCodigoBarras'), expectOfereceFatAberto],
                [expectOfereceFatAberto, aceitaCodBarras],
                    [aceitaCodBarras.getPath('Aceita receber Código de Barras'), servicoCodigoBarras5],
                    [aceitaCodBarras.getPath('Não aceita receber Código de Barras'), expectNaoAceitaCodBarra],
                        [expectNaoAceitaCodBarra, clienteInsiste],
                            [clienteInsiste.getPath('Quer algo mais: #desambiguadorCodigoBarras ou SegundaVia ou Pagar Conta ou NaoRecebimentoFatura'), insisteFaturasAberto],
                                [insisteFaturasAberto.getPath('* (insistencia) Não possui faturas em aberto'), insisteFaturasAbertoNao],
                                    [insisteFaturasAbertoNao, perguntaQuerAlgoMais],
                                [insisteFaturasAberto.getPath('* (insistencia) Possui faturas em aberto'), insisteFaturasAbertoSim],
                                    [insisteFaturasAbertoSim, perguntaQuerAlgoMais],
                            [clienteInsiste.getPath('Não quer mais nada').noStepMessage(), perguntaQuerAlgoMais],

                [faturaEmAberto.getPath('* Não possui fatura em aberto'), expectNaoPossuiFaturaAberto],
                    [expectNaoPossuiFaturaAberto, perguntaQuerAlgoMais],
            //        
            [mainClienteTitular.getPath('* É titular'), pediuAlgumMes],
                [pediuAlgumMes.getPath('Fatura de um mês espefícico'), mesPossuiFaturaAberto],
                    [mesPossuiFaturaAberto.getPath('Mês não está nas faturas em aberto'), faturaUltimos12meses],
                        [faturaUltimos12meses.getPath('Não é dos últimos 12 meses'), expectNaoUltimos12meses],
                            [expectNaoUltimos12meses, transfereParaATH],
                        [faturaUltimos12meses.getPath('É dos últimos 12 meses').noStepMessage(), faturaUltimos6meses],
                            [faturaUltimos6meses.getPath('Não é dos ultimos 6 meses'), expectNaoUltimos6meses],
                                [expectNaoUltimos6meses, querContinuarURA],
                                    [querContinuarURA.getPath('Quer continuar com o ATH'), transfereParaATH],
                                    [querContinuarURA.getPath('Quer continuar com a URA'), verificaProprioAparelhoSMS],
                                    //
                            [faturaUltimos6meses.getPath('É dos ultimos 6 meses'), emailValido],
                                [emailValido.getPath('* Email inválido'), expectEmailInvalido],
                                    [expectEmailInvalido, verificaProprioAparelhoSMS],
                                [emailValido.getPath('* Email válido'), expectComoPrefere],
                                    [expectComoPrefere, escolhaRealizada],
                                        [escolhaRealizada.getPath('Quer receber por SMS'), verificaProprioAparelhoSMS],
                                            [verificaProprioAparelhoSMS.getPath('* Ligando do próprio aparelho'), servicoFaturaSMS1],
                                                [servicoFaturaSMS1.getPath('* Falha no serviço SMS').noStepMessage(), servicoCodigoBarras5.getPath('* Falha Serviço Cód.Barras/SMS')],
                                                [servicoFaturaSMS1.getPath('* Sucesso no serviço SMS'), existemFaturasAbertoSMS],
                                                    [existemFaturasAbertoSMS, clienteContaDigital],
                                                        [clienteContaDigital, perguntaQuerAlgoMais],
                                                            [expectTratNaoRecebimento, perguntaQuerAlgoMais],
                                                        [expectFaturasEmAbertoSMS, querReceberFatEmAbertoSMS],
                                                        [querReceberFatEmAbertoSMS.getPath('Não quer receber faturas em aberto'), clienteContaDigital],
                                                        [querReceberFatEmAbertoSMS.getPath('Quer receber faturas em aberto'), enviaFaturasEmAbertoSMS],
                                                        [enviaFaturasEmAbertoSMS, clienteContaDigital],
                                            [verificaProprioAparelhoSMS.getPath('* Ligando de outro aparelho'), expectOutroAparelhoSMS],
                                                [expectOutroAparelhoSMS, fluxoSenhaSMS],
                                                    [fluxoSenhaSMS.getPath('* Senha Incorreta'), ofereceATH],
                                                    [fluxoSenhaSMS.getPath('* Sucesso no Fluxo de Senha'), servicoFaturaSMS1],
                                        // FIM SMS
                                        [escolhaRealizada.getPath('Quer receber por Email'), verificaProprioAparelhoEmail],
                                        [verificaProprioAparelhoEmail.getPath('* Ligando do próprio aparelho'), servicoFaturaEmail1],
                                            [servicoFaturaEmail1.getPath('* Sucesso no serviço Email'), existemFaturasAbertoEmail],
                                                [existemFaturasAbertoEmail, clienteContaDigital],
                                                    [expectFaturasEmAbertoEmail, querReceberFatEmAbertoEmail],
                                                    [querReceberFatEmAbertoEmail.getPath('Não quer receber faturas em aberto'), clienteContaDigital],
                                                    [querReceberFatEmAbertoEmail.getPath('Quer receber faturas em aberto'), enviaFaturasEmAbertoEmail],
                                                    [enviaFaturasEmAbertoEmail, clienteContaDigital],
                                        [verificaProprioAparelhoEmail.getPath('* Ligando de outro aparelho'), expectOutroAparelhoEmail],
                                            [expectOutroAparelhoEmail, fluxoSenhaEmail],
                                                [fluxoSenhaEmail.getPath('* Senha Incorreta'), ofereceATH],
                                                [fluxoSenhaEmail.getPath('* Sucesso no Fluxo de Senha'), servicoFaturaEmail1],
                                        // FIM EMAIL
                                        [escolhaRealizada.getPath('Quer receber em Casa'), expectEscolheCasa],
                                            [expectEscolheCasa, confirmaCasa],
                                            [confirmaCasa.getPath('Aceita receber por e-mail'), verificaProprioAparelhoEmail],
                                            [confirmaCasa.getPath('Insiste receber em casa'), verificaProprioAparelhoCasa],
                                            // COMEÇA
                                            [verificaProprioAparelhoCasa.getPath('* Ligando do próprio aparelho'), servicoFaturaCasa1],
                                                [servicoFaturaCasa1.getPath('* Sucesso no serviço Correios'), existemFaturasAbertoCasa],
                                                    [existemFaturasAbertoCasa, clienteContaDigital],
                                                        [expectFaturasEmAbertoCasa, querReceberFatEmAbertoCasa],
                                                        [querReceberFatEmAbertoCasa.getPath('Não quer receber faturas em aberto'), clienteContaDigital],
                                                        [querReceberFatEmAbertoCasa.getPath('Quer receber faturas em aberto'), enviaFaturasEmAbertoCasa],
                                                        [enviaFaturasEmAbertoCasa, clienteContaDigital],
                                            [verificaProprioAparelhoCasa.getPath('* Ligando de outro aparelho'), expectOutroAparelhoCasa],
                                                [expectOutroAparelhoCasa, fluxoSenhaCasa],
                                                    [fluxoSenhaCasa.getPath('* Senha Incorreta'), ofereceATH],
                                                    [fluxoSenhaCasa.getPath('* Sucesso no Fluxo de Senha'), servicoFaturaCasa1],
                                        // FIM CASA
                                        [escolhaRealizada.getPath('Escolha inválida'), expectSegundaChance],
                                            [expectSegundaChance, ofereceSegundaChance],
                                            [ofereceSegundaChance.getPath('Escolhe receber SMS (Segunda tentativa)'), verificaProprioAparelhoSMS],
                                            [ofereceSegundaChance.getPath('Escolhe receber Email (Segunda tentativa)'), verificaProprioAparelhoEmail],
                                            [ofereceSegundaChance.getPath('Escolhe receber em Casa (Segunda tentativa)'), expectEscolheCasa],
                                            [ofereceSegundaChance.getPath('Escolha inválida (Segunda tentativa)'), verificaProprioAparelhoSMS],
                    [mesPossuiFaturaAberto.getPath('Mês está nas faturas em aberto'), emailValidoAlt],

                [pediuAlgumMes.getPath('Não pediu mês específico'), semMesFaturaAberto],
                    [semMesFaturaAberto.getPath('* Não possui fatura em aberto'), expectSemMesNaoPossuiFatura],
                        [expectSemMesNaoPossuiFatura, precisaSegundaVia],
                            [precisaSegundaVia.getPath('Não precisa de segunda via'), perguntaQuerAlgoMais],
                            [precisaSegundaVia.getPath('Precisa de segunda via'), expectPrecisaSegundaVia],
                                [expectPrecisaSegundaVia, qualMesSegundaVia],
                                    [qualMesSegundaVia.getPath('Mês válido'), faturaUltimos12mesesAlt],
                                        [faturaUltimos12mesesAlt.getPath('Fatura não é dos ultimos 12 meses'), expectNaoUltimos12mesesAlt],
                                            [expectNaoUltimos12mesesAlt, transfereParaATH],
                                        [faturaUltimos12mesesAlt.getPath('Fatura dos ultimos 12 meses').noStepMessage(), faturaUltimos6mesesAlt],
                                            [faturaUltimos6mesesAlt.getPath('Não é dos ultimos 6 meses'), expectNaoUltimos6mesesAlt],
                                                [expectNaoUltimos6mesesAlt, querContinuarURAAlt],
                                                    [querContinuarURAAlt.getPath('Quer continuar com o ATH'), transfereParaATH],
                                                    [querContinuarURAAlt.getPath('Quer continuar com a URA'), verificaProprioAparelhoSMSAlt2],
                                                        [verificaProprioAparelhoSMSAlt2.getPath('* Ligando do próprio aparelho'), servicoLinkNegocia2],
                                                            [servicoLinkNegocia2.getPath('Link Negocia enviado'), enviaLinkNegocia],
                                                                [enviaLinkNegocia, perguntaQuerAlgoMais],
                                                        [verificaProprioAparelhoSMSAlt2.getPath('* Ligando de outro aparelho'), expectOutroAparelhoSMSAlt2],
                                                            [expectOutroAparelhoSMSAlt2, fluxoSenhaSMSAlt2],
                                                                [fluxoSenhaSMSAlt2.getPath('* Senha Incorreta'), ofereceATH],
                                                                [fluxoSenhaSMSAlt2.getPath('* Sucesso no Fluxo de Senha'), servicoLinkNegocia2],
                                                                //
                                            [faturaUltimos6mesesAlt.getPath('É dos ultimos 6 meses'), emailValidoAlt],
                                            
                                        //
                                    [qualMesSegundaVia.getPath('Mês inválido'), expectMesInvalido],
                                        [expectMesInvalido, segundaTentativaMes],
                                            [segundaTentativaMes.getPath('Mês válido (segunda tentativa)'), faturaUltimos12mesesAlt],
                                            [segundaTentativaMes.getPath('Mês inválido (segunda tentativa)'), ofereceATH],

                    [semMesFaturaAberto.getPath('* Possui fatura em aberto'), emailValidoAlt],
                        [emailValidoAlt.getPath('* Email inválido'), expectEmailInvalidoAlt],
                            [expectEmailInvalidoAlt, verificaProprioAparelhoSMSAlt],
                        [emailValidoAlt.getPath('* Email válido'), expectComoPrefereAlt],
                            [expectComoPrefereAlt, escolhaRealizadaAlt],
                                [escolhaRealizadaAlt.getPath('Quer receber por SMS'), verificaProprioAparelhoSMSAlt],
                                    [verificaProprioAparelhoSMSAlt.getPath('* Ligando do próprio aparelho'), servicoFaturaSMS1Alt],
                                        [servicoFaturaSMS1Alt.getPath('* Falha no serviço SMS').noStepMessage(), servicoCodigoBarras5.getPath('* Falha Serviço Cód.Barras/SMS')],
                                        [servicoFaturaSMS1Alt.getPath('* Sucesso no serviço SMS'), clienteContaDigital],
                                    [verificaProprioAparelhoSMSAlt.getPath('* Ligando de outro aparelho'), expectOutroAparelhoSMSAlt],
                                    [expectOutroAparelhoSMSAlt, fluxoSenhaSMSAlt],
                                        [fluxoSenhaSMSAlt.getPath('* Senha Incorreta'), ofereceATH],
                                        [fluxoSenhaSMSAlt.getPath('* Sucesso no Fluxo de Senha'), servicoFaturaSMS1Alt],
                                // FIM SMS
                                [escolhaRealizadaAlt.getPath('Quer receber por Email'), verificaProprioAparelhoEmailAlt],
                                        [verificaProprioAparelhoEmailAlt.getPath('* Ligando do próprio aparelho'), servicoFaturaEmail1Alt],
                                            [servicoFaturaEmail1Alt.getPath('* Sucesso no serviço Email'), clienteContaDigital],
                                            [servicoFaturaEmail1Alt.getPath('* Falha no serviço Email').noStepMessage(), servicoFaturaEmail1.getPath('* Falha no serviço Email')],
                                        [verificaProprioAparelhoEmailAlt.getPath('* Ligando de outro aparelho'), expectOutroAparelhoEmailAlt],
                                            [expectOutroAparelhoEmailAlt, fluxoSenhaEmailAlt],
                                                [fluxoSenhaEmailAlt.getPath('* Senha Incorreta'), ofereceATH],
                                                [fluxoSenhaEmailAlt.getPath('* Sucesso no Fluxo de Senha'), servicoFaturaEmail1Alt],
                                // FIM EMAIL
                                [escolhaRealizadaAlt.getPath('Quer receber em Casa'), expectEscolheCasaAlt],
                                    [expectEscolheCasaAlt, confirmaCasaAlt],
                                        [confirmaCasaAlt.getPath('Aceita receber por e-mail'), verificaProprioAparelhoEmailAlt],
                                        [confirmaCasaAlt.getPath('Insiste receber em casa'), verificaProprioAparelhoCasaAlt],
                                            // COMEÇA
                                            [verificaProprioAparelhoCasaAlt.getPath('* Ligando do próprio aparelho'), servicoFaturaCasa1Alt],
                                                [servicoFaturaCasa1Alt.getPath('* Sucesso no serviço Correios'), clienteContaDigital],
                                                [servicoFaturaCasa1Alt.getPath('* Falha no serviço Correios').noStepMessage(), servicoFaturaCasa1.getPath('* Falha no serviço Correios')],
                                            [verificaProprioAparelhoCasaAlt.getPath('* Ligando de outro aparelho'), expectOutroAparelhoCasaAlt],
                                                [expectOutroAparelhoCasaAlt, fluxoSenhaCasaAlt],
                                                    [fluxoSenhaCasaAlt.getPath('* Senha Incorreta'), ofereceATH],
                                                    [fluxoSenhaCasaAlt.getPath('* Sucesso no Fluxo de Senha'), servicoFaturaCasa1Alt],
                                // FIM CASA

        [billingProfile.getPath('* Falha no billing'), veioDeNaoRecebimentoFaturaERRO],
            [veioDeNaoRecebimentoFaturaERRO, mainClienteTitularERRO],
            // [mainClienteTitularERRO.getPath('* Não é titular'), faturaEmAbertoERRO],
                [faturaEmAbertoERRO.getPath('* Possui fatura em aberto'), intencaoCodigoBarrasERRO],
                [intencaoCodigoBarrasERRO.getPath('VEIO DE DESAMBIGUADOR CODIGOBARRAS'), servicoCodigoBarras5ERRO],
                    [servicoCodigoBarras5ERRO.getPath('* Sucesso Serviço Cód.Barras/SMS'), maisDe1FaturaAbertoERRO],
                        [maisDe1FaturaAbertoERRO.getPath('* Não possui mais de 1 fatura em aberto'), mais1FaturaNaoERRO],
                            [mais1FaturaNaoERRO, perguntaQuerAlgoMaisERRO],
                        [maisDe1FaturaAbertoERRO.getPath('* Possui mais de 1 fatura em aberto'), mais1FaturaSimERRO],
                            [mais1FaturaSimERRO, perguntaQuerAlgoMaisERRO],
                [intencaoCodigoBarrasERRO.getPath('Não veio de desambiguadorCodigoBarras'), expectOfereceFatAbertoERRO],
                [expectOfereceFatAbertoERRO, aceitaCodBarrasERRO],
                    [aceitaCodBarrasERRO.getPath('Aceita receber Código de Barras'), servicoCodigoBarras5ERRO],
                    [aceitaCodBarrasERRO.getPath('Não aceita receber Código de Barras'), expectNaoAceitaCodBarraERRO],
                        [expectNaoAceitaCodBarraERRO, clienteInsisteERRO],
                            [clienteInsisteERRO.getPath('Quer algo mais: #desambiguadorCodigoBarras ou SegundaVia ou Pagar Conta ou NaoRecebimentoFatura'), insisteFaturasAbertoERRO],
                                [insisteFaturasAbertoERRO.getPath('* (insistencia) Não possui faturas em aberto'), insisteFaturasAbertoNaoERRO],
                                    [insisteFaturasAbertoNaoERRO, perguntaQuerAlgoMaisERRO],
                                [insisteFaturasAbertoERRO.getPath('* (insistencia) Possui faturas em aberto'), insisteFaturasAbertoSimERRO],
                                    [insisteFaturasAbertoSimERRO, perguntaQuerAlgoMaisERRO],
                            [clienteInsisteERRO.getPath('Não quer mais nada').noStepMessage(), perguntaQuerAlgoMaisERRO],

                [faturaEmAbertoERRO.getPath('* Não possui fatura em aberto'), expectNaoPossuiFaturaAbertoERRO],
                    [expectNaoPossuiFaturaAbertoERRO, perguntaQuerAlgoMaisERRO],
            //        
            [mainClienteTitularERRO.getPath('* É titular'), pediuAlgumMesERRO],
                [pediuAlgumMesERRO.getPath('Fatura de um mês espefícico'), mesPossuiFaturaAbertoERRO],
                    [mesPossuiFaturaAbertoERRO.getPath('Mês não está nas faturas em aberto'), faturaUltimos12mesesERRO],
                        [faturaUltimos12mesesERRO.getPath('Não é dos últimos 12 meses'), expectNaoUltimos12mesesERRO],
                            [expectNaoUltimos12mesesERRO, transfereParaATHERRO],
                        [faturaUltimos12mesesERRO.getPath('É dos últimos 12 meses').noStepMessage(), faturaUltimos6mesesERRO],
                            [faturaUltimos6mesesERRO.getPath('Não é dos ultimos 6 meses'), expectNaoUltimos6mesesERRO],
                                [expectNaoUltimos6mesesERRO, querContinuarURAERRO],
                                    [querContinuarURAERRO.getPath('Quer continuar com o ATH'), transfereParaATHERRO],
                                    [querContinuarURAERRO.getPath('Quer continuar com a URA'), verificaProprioAparelhoSMSERRO],
                                    //
                            [faturaUltimos6mesesERRO.getPath('É dos ultimos 6 meses'), emailValidoERRO],
                                [emailValidoERRO.getPath('* Email inválido'), expectEmailInvalidoERRO],
                                    [expectEmailInvalidoERRO, verificaProprioAparelhoSMSERRO],
                                [emailValidoERRO.getPath('* Email válido'), expectComoPrefereERRO],
                                    [expectComoPrefereERRO, escolhaRealizadaERRO],
                                        [escolhaRealizadaERRO.getPath('Quer receber por SMS'), verificaProprioAparelhoSMSERRO],
                                            [verificaProprioAparelhoSMSERRO.getPath('* Ligando do próprio aparelho'), servicoFaturaSMS1ERRO],
                                                [servicoFaturaSMS1ERRO.getPath('* Falha no serviço SMS').noStepMessage(), servicoCodigoBarras5ERRO.getPath('* Falha Serviço Cód.Barras/SMS')],
                                                [servicoFaturaSMS1ERRO.getPath('* Sucesso no serviço SMS'), existemFaturasAbertoSMSERRO],
                                                    [existemFaturasAbertoSMSERRO, perguntaQuerAlgoMaisERRO],
                                                            [expectTratNaoRecebimentoERRO, perguntaQuerAlgoMaisERRO],
                                                        [expectFaturasEmAbertoSMSERRO, querReceberFatEmAbertoSMSERRO],
                                                        [querReceberFatEmAbertoSMSERRO.getPath('Não quer receber faturas em aberto'), clienteContaDigitalERRO],
                                                        [querReceberFatEmAbertoSMSERRO.getPath('Quer receber faturas em aberto'), enviaFaturasEmAbertoSMSERRO],
                                                        [enviaFaturasEmAbertoSMSERRO, clienteContaDigitalERRO],
                                            [verificaProprioAparelhoSMSERRO.getPath('* Ligando de outro aparelho'), expectOutroAparelhoSMSERRO],
                                                [expectOutroAparelhoSMSERRO, fluxoSenhaSMSERRO],
                                                    [fluxoSenhaSMSERRO.getPath('* Senha Incorreta'), ofereceATHERRO],
                                                    [fluxoSenhaSMSERRO.getPath('* Sucesso no Fluxo de Senha'), servicoFaturaSMS1ERRO],
                                        // FIM SMS
                                        // [escolhaRealizadaERRO.getPath('Quer receber por Email'), verificaProprioAparelhoEmailERRO],
                                        [verificaProprioAparelhoEmailERRO.getPath('* Ligando do próprio aparelho'), servicoFaturaEmail1ERRO],
                                            [servicoFaturaEmail1ERRO.getPath('* Sucesso no serviço Email'), existemFaturasAbertoEmailERRO],
                                                [existemFaturasAbertoEmailERRO, clienteContaDigitalERRO],
                                                    [expectFaturasEmAbertoEmailERRO, querReceberFatEmAbertoEmailERRO],
                                                    [querReceberFatEmAbertoEmailERRO.getPath('Não quer receber faturas em aberto'), clienteContaDigitalERRO],
                                                    [querReceberFatEmAbertoEmailERRO.getPath('Quer receber faturas em aberto'), enviaFaturasEmAbertoEmailERRO],
                                                    [enviaFaturasEmAbertoEmailERRO, clienteContaDigitalERRO],
                                        [verificaProprioAparelhoEmailERRO.getPath('* Ligando de outro aparelho'), expectOutroAparelhoEmailERRO],
                                            [expectOutroAparelhoEmailERRO, fluxoSenhaEmailERRO],
                                                [fluxoSenhaEmailERRO.getPath('* Senha Incorreta'), ofereceATHERRO],
                                                [fluxoSenhaEmailERRO.getPath('* Sucesso no Fluxo de Senha'), servicoFaturaEmail1ERRO],
                                        // FIM EMAIL
                                        // [escolhaRealizadaERRO.getPath('Quer receber em Casa'), expectEscolheCasaERRO],
                                            [expectEscolheCasaERRO, confirmaCasaERRO],
                                            [confirmaCasaERRO.getPath('Aceita receber por e-mail'), verificaProprioAparelhoEmailERRO],
                                            [confirmaCasaERRO.getPath('Insiste receber em casa'), verificaProprioAparelhoCasaERRO],
                                            // COMEÇA
                                            [verificaProprioAparelhoCasaERRO.getPath('* Ligando do próprio aparelho'), servicoFaturaCasa1ERRO],
                                                [servicoFaturaCasa1ERRO.getPath('* Sucesso no serviço Correios'), existemFaturasAbertoCasaERRO],
                                                    [existemFaturasAbertoCasaERRO, clienteContaDigitalERRO],
                                                        [expectFaturasEmAbertoCasaERRO, querReceberFatEmAbertoCasaERRO],
                                                        [querReceberFatEmAbertoCasaERRO.getPath('Não quer receber faturas em aberto'), clienteContaDigitalERRO],
                                                        [querReceberFatEmAbertoCasaERRO.getPath('Quer receber faturas em aberto'), enviaFaturasEmAbertoCasaERRO],
                                                        [enviaFaturasEmAbertoCasaERRO, clienteContaDigitalERRO],
                                            [verificaProprioAparelhoCasaERRO.getPath('* Ligando de outro aparelho'), expectOutroAparelhoCasaERRO],
                                                [expectOutroAparelhoCasaERRO, fluxoSenhaCasaERRO],
                                                    [fluxoSenhaCasaERRO.getPath('* Senha Incorreta'), ofereceATHERRO],
                                                    [fluxoSenhaCasaERRO.getPath('* Sucesso no Fluxo de Senha'), servicoFaturaCasa1ERRO],
                                        // FIM CASA
                                        [escolhaRealizadaERRO.getPath('Escolha inválida'), expectSegundaChanceERRO],
                                            [expectSegundaChanceERRO, ofereceSegundaChanceERRO],
                                            [ofereceSegundaChanceERRO.getPath('Escolhe receber SMS (Segunda tentativa)'), verificaProprioAparelhoSMSERRO],
                                            [ofereceSegundaChanceERRO.getPath('Escolhe receber Email (Segunda tentativa)'), verificaProprioAparelhoEmailERRO],
                                            [ofereceSegundaChanceERRO.getPath('Escolhe receber em Casa (Segunda tentativa)'), expectEscolheCasaERRO],
                                            [ofereceSegundaChanceERRO.getPath('Escolha inválida (Segunda tentativa)'), verificaProprioAparelhoSMSERRO],
                    [mesPossuiFaturaAbertoERRO.getPath('Mês está nas faturas em aberto'), emailValidoAltERRO],

                [pediuAlgumMesERRO.getPath('Não pediu mês específico'), semMesFaturaAbertoERRO],
                    [semMesFaturaAbertoERRO.getPath('* Não possui fatura em aberto'), expectSemMesNaoPossuiFaturaERRO],
                        [expectSemMesNaoPossuiFaturaERRO, precisaSegundaViaERRO],
                            [precisaSegundaViaERRO.getPath('Não precisa de segunda via'), perguntaQuerAlgoMaisERRO],
                            [precisaSegundaViaERRO.getPath('Precisa de segunda via'), expectPrecisaSegundaViaERRO],
                                [expectPrecisaSegundaViaERRO, qualMesSegundaViaERRO],
                                    [qualMesSegundaViaERRO.getPath('Mês válido'), faturaUltimos12mesesAltERRO],
                                        [faturaUltimos12mesesAltERRO.getPath('Fatura não é dos ultimos 12 meses'), expectNaoUltimos12mesesAltERRO],
                                            [expectNaoUltimos12mesesAltERRO, transfereParaATHERRO],
                                        [faturaUltimos12mesesAltERRO.getPath('Fatura dos ultimos 12 meses').noStepMessage(), faturaUltimos6mesesAltERRO],
                                            [faturaUltimos6mesesAltERRO.getPath('Não é dos ultimos 6 meses'), expectNaoUltimos6mesesAltERRO],
                                                [expectNaoUltimos6mesesAltERRO, querContinuarURAAltERRO],
                                                    [querContinuarURAAltERRO.getPath('Quer continuar com o ATH'), transfereParaATHERRO],
                                                    [querContinuarURAAltERRO.getPath('Quer continuar com a URA'), verificaProprioAparelhoSMSAlt2ERRO],
                                                        [verificaProprioAparelhoSMSAlt2ERRO.getPath('* Ligando do próprio aparelho'), servicoLinkNegocia2ERRO],
                                                            [servicoLinkNegocia2ERRO.getPath('Link Negocia enviado'), enviaLinkNegociaERRO],
                                                                [enviaLinkNegociaERRO, perguntaQuerAlgoMaisERRO],
                                                        [verificaProprioAparelhoSMSAlt2ERRO.getPath('* Ligando de outro aparelho'), expectOutroAparelhoSMSAlt2ERRO],
                                                            [expectOutroAparelhoSMSAlt2ERRO, fluxoSenhaSMSAlt2ERRO],
                                                                [fluxoSenhaSMSAlt2ERRO.getPath('* Senha Incorreta'), ofereceATHERRO],
                                                                [fluxoSenhaSMSAlt2ERRO.getPath('* Sucesso no Fluxo de Senha'), servicoLinkNegocia2ERRO],
                                                                //
                                            [faturaUltimos6mesesAltERRO.getPath('É dos ultimos 6 meses'), emailValidoAltERRO],
                                            
                                        //
                                    [qualMesSegundaViaERRO.getPath('Mês inválido'), expectMesInvalidoERRO],
                                        [expectMesInvalidoERRO, segundaTentativaMesERRO],
                                            [segundaTentativaMesERRO.getPath('Mês válido (segunda tentativa)'), faturaUltimos12mesesAltERRO],
                                            [segundaTentativaMesERRO.getPath('Mês inválido (segunda tentativa)'), ofereceATHERRO],

                    [semMesFaturaAbertoERRO.getPath('* Possui fatura em aberto'), emailValidoAltERRO],
                        [emailValidoAltERRO.getPath('* Email inválido'), expectEmailInvalidoAltERRO],
                            [expectEmailInvalidoAltERRO, verificaProprioAparelhoSMSAltERRO],
                        [emailValidoAltERRO.getPath('* Email válido'), expectComoPrefereAltERRO],
                            [expectComoPrefereAltERRO, escolhaRealizadaAltERRO],
                                [escolhaRealizadaAltERRO.getPath('Quer receber por SMS'), verificaProprioAparelhoSMSAltERRO],
                                    [verificaProprioAparelhoSMSAltERRO.getPath('* Ligando do próprio aparelho'), servicoFaturaSMS1AltERRO],
                                        [servicoFaturaSMS1AltERRO.getPath('* Falha no serviço SMS').noStepMessage(), servicoCodigoBarras5ERRO.getPath('* Falha Serviço Cód.Barras/SMS')],
                                        [servicoFaturaSMS1AltERRO.getPath('* Sucesso no serviço SMS'), clienteContaDigitalERRO],
                                    [verificaProprioAparelhoSMSAltERRO.getPath('* Ligando de outro aparelho'), expectOutroAparelhoSMSAltERRO],
                                    [expectOutroAparelhoSMSAltERRO, fluxoSenhaSMSAltERRO],
                                        [fluxoSenhaSMSAltERRO.getPath('* Senha Incorreta'), ofereceATHERRO],
                                        [fluxoSenhaSMSAltERRO.getPath('* Sucesso no Fluxo de Senha'), servicoFaturaSMS1AltERRO],
                                // FIM SMS
                                // [escolhaRealizadaAltERRO.getPath('Quer receber por Email'), verificaProprioAparelhoEmailAltERRO],
                                        [verificaProprioAparelhoEmailAltERRO.getPath('* Ligando do próprio aparelho'), servicoFaturaEmail1AltERRO],
                                            [servicoFaturaEmail1AltERRO.getPath('* Sucesso no serviço Email'), clienteContaDigitalERRO],
                                            [servicoFaturaEmail1AltERRO.getPath('* Falha no serviço Email').noStepMessage(), servicoFaturaEmail1ERRO.getPath('* Falha no serviço Email')],
                                        [verificaProprioAparelhoEmailAltERRO.getPath('* Ligando de outro aparelho'), expectOutroAparelhoEmailAltERRO],
                                            [expectOutroAparelhoEmailAltERRO, fluxoSenhaEmailAltERRO],
                                                [fluxoSenhaEmailAltERRO.getPath('* Senha Incorreta'), ofereceATHERRO],
                                                [fluxoSenhaEmailAltERRO.getPath('* Sucesso no Fluxo de Senha'), servicoFaturaEmail1AltERRO],
                                // FIM EMAIL
                                // [escolhaRealizadaAltERRO.getPath('Quer receber em Casa'), expectEscolheCasaAltERRO],
                                    [expectEscolheCasaAltERRO, confirmaCasaAltERRO],
                                        [confirmaCasaAltERRO.getPath('Aceita receber por e-mail'), verificaProprioAparelhoEmailAltERRO],
                                        [confirmaCasaAltERRO.getPath('Insiste receber em casa'), verificaProprioAparelhoCasaAltERRO],
                                            // COMEÇA
                                            [verificaProprioAparelhoCasaAltERRO.getPath('* Ligando do próprio aparelho'), servicoFaturaCasa1AltERRO],
                                                [servicoFaturaCasa1AltERRO.getPath('* Sucesso no serviço Correios'), clienteContaDigitalERRO],
                                                [servicoFaturaCasa1AltERRO.getPath('* Falha no serviço Correios').noStepMessage(), servicoFaturaCasa1ERRO.getPath('* Falha no serviço Correios')],
                                            [verificaProprioAparelhoCasaAltERRO.getPath('* Ligando de outro aparelho'), expectOutroAparelhoCasaAltERRO],
                                                [expectOutroAparelhoCasaAltERRO, fluxoSenhaCasaAltERRO],
                                                    [fluxoSenhaCasaAltERRO.getPath('* Senha Incorreta'), ofereceATHERRO],
                                                    [fluxoSenhaCasaAltERRO.getPath('* Sucesso no Fluxo de Senha'), servicoFaturaCasa1AltERRO],
                                // FIM CASA
    

)


pagarConta.mapScenarios();
// pagarConta.showScenarios();
pagarConta.exportScenariosToText();
pagarConta.exportScenariosToExcel();